name: pockerledger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/achieve_goals.svg
    - assets/images/set_budget.svg
    - assets/images/track_expenses.svg
