name: pocketledger
description: "### Personal Finance App - Your Financial Companion.Take control of your finances with our Personal Finance App! Designed to simplify your financial life, our app offers a comprehensive suite of features to help you manage your money effortlessly. Track your spending, set budgets, monitor your savings goals, and get insightful reports—all in one place. With intuitive navigation and real-time updates, staying on top of your finances has never been easier. Start your journey to financial freedom today! 💰📊Download now and transform the way you handle your money!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/achieve_goals.svg
    - assets/images/set_budget.svg
    - assets/images/track_expenses.svg
    - assets/images/profile.png
